### ISSUE TITLE
Add option to throw `IllegalArgumentException` instead of `NullPointerException`

### ISSUE THREAD

**Issue by odrotbohm** [xzel23/cabe#14]
Rejecting `null` arguments with a `NPE` is suboptimal as it blurs the line between caller error and callee error, as the rejection of a parameter is indistinguishable from an accidental null-dereference somewhere in the called code. That's why many assertion APIs (most notably Spring Framework's `Assert.notNull(…)`) rather throws `IllegalArgumentException`, as `IAE` clearly signals the error resides on the caller side.

Thuis, it would be nice if Cabe could be configured to reject null parameters with an `IllegalArgumentException`.

**Comment by xzel23** [comment]
Ok, will be added in the next version.

**Comment by xzel23** [comment]
Just published 3.0.1 with this enhancement.

**Comment by odrotbohm** [comment]
That was fast! Thank you very much! 🙇
